default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  connect_timeout: 5
  checkout_timeout: 5
  idle_timeout: 300
  variables:
    statement_timeout: "30000"

development:
  <<: *default
  database: trainspotters_intl_development

test:
  <<: *default
  database: trainspotters_intl_test

production:
  <<: *default
  database: trainspotters_intl_production
  username: trainspotters_intl
  password: <%= ENV['TRAINSPOTTERS_INTL_DATABASE_PASSWORD'] %>
